<?php

return [
    'RESPONSE_CONSTANTS' => [
        'STATUS_ERROR' => 0,
        'STATUS_SUCCESS' => 1,
        'STATUS_OTHER_ERROR' => 2,
        'STATUS_ACCOUNT_UNAUTHORIZED' => 3,
        'STATUS_ACCOUNT_DEACTIVATED' => 4,
        'STATUS_ACCOUNT_DELETED' => 5,
        'STATUS_INVALID_TOKEN' => 6,
        'STATUS_INVALID_USER_TYPE' => 7,
        'STATUS_INVALID_COUPON_CODE' => 8,
        'STATUS_INVALID_AVAILABLE_QUANTITY' => 9,
        'STATUS_INVALID_PRODUCT_QUANTITY' => 10,
        'INVALID_PARAMETERS' => 'Invalid Request Parameters.',
        'ERROR_EMAIL_EXIST' => 'Email Already In Use.',
        'ERROR_PHONE_EXIST' => 'Phone Already In Use.',
        'ERROR_USER_NAME_EXIST' => 'User Name Already In Use.',
        'ERROR_INVALID_CREDENTIALS' => 'Invalid Email or Password.',
        'ERROR_ACCOUNT_SUSPENDED' => 'Your Account Has Been Suspended.',
        'ERROR_ACCOUNT_DELETED' => 'Your Account Has Been Deleted.',
        'ERROR_ACCOUNT_UNAUTHORIZED' => 'Your Account Is Not Authorized Yet.',
        'ERROR_INVALID_EMAIL' => 'Invalid Email Address.',
        'ERROR_INVALID_USER_TYPE' => 'Invalid User Type.',
        'ERROR_INVALID_COUPON_CODE' => 'Invalid Coupon Code.',
        'MSG_LOGGED_IN' => 'Logged In Successfully.',
        'MSG_REGISTERED_SUCCESS' => 'Registered Successfully.',
        'MSG_REGISTERED_PROFESSIONAL' => 'Registered Successfully. You can login once your account is approved.',
        'MSG_LOGGED_OUT' => 'Logged out successfully.',
    ],

    'GENERAL_CONSTANTS' => [
        'KEY_PAGE_NO' => 'page_no',
        'KEY_PAGE_ID' => 'page_id',
    ],

    'PATIENT_CONSTANTS' => [
        'KEY_PATIENT_ID' => 'patient_id',
        'KEY_PRACTITIONER_ID' => 'practitioner_id',
        'KEY_FULL_NAME' => 'full_name',
        'KEY_EMAIL' => 'email',
        'KEY_PASSWORD' => 'password',
        'KEY_PHONE' => 'phone',
        'KEY_DATE_OF_BIRTH' => 'dob',
        'KEY_AGE' => 'age',
        'KEY_GENDER' => 'gender',
        'KEY_PROFILE_IMAGE' => 'profile_image',
        'KEY_WEIGHT_KGS' => 'weight_kgs',
        'KEY_WEIGHT_LBS' => 'weight_lbs',
        'KEY_HEIGHT_FT' => 'height_ft',
        'KEY_HEIGHT_IN' => 'height_in',
        'KEY_HEIGHT_CMS' => 'height_cms',
        'KEY_MARITAL_STATUS' => 'marital_status',
        'KEY_HOSPITALIZATION' => 'hospitalization',
        'KEY_CURRENTLY_ON_DRUG' => 'currently_on_drug',
        'KEY_ADDRESS' => 'address',
        'KEY_DRUGS' => 'drugs',
        'KEY_ALLERGIES' => 'allergies',
        'KEY_DEVICE_ID' => 'device_id',
        'KEY_DEVICE_TYPE' => 'device_type',
        'KEY_SOCIAL_ID' => 'social_id',
        'KEY_LOGIN_TYPE' => 'login_type',
        'KEY_STATUS_NOTIFICATION' => 'status_notification',
        'KEY_OFFER_NOTIFICATION' => 'offer_notification',
        'KEY_FILE_TITLE' => 'file_title',
        'KEY_FILE_TYPE' => 'file_type',
        'KEY_UPLOAD_FILE' => 'upload_file',
        'KEY_ATTACHMENT_ID' => 'attachment_id',
        'KEY_SPECIALTY_ID' => 'specialty_id',
        'KEY_NOTIFICATION_ID' => 'notification_id',
    ],

    'APPOINTMENT_CONSTANTS' => [
        'KEY_APPOINTMENT_ID' => 'appointment_id',
        'KEY_PATIENT_ID' => 'patient_id',
        'KEY_PRACTITIONER_ID' => 'practitioner_id',
        'KEY_CLINIC_ID' => 'clinic_id',
        'KEY_APPOINTMENT_TYPE' => 'appointment_type',
        'KEY_DATE' => 'date',
        'KEY_TIME_SLOT' => 'time_slot',
        'KEY_FEE' => 'fee',
        'KEY_PAYMENT_METHOD' => 'payment_method',
    ],

    'PRACTITIONER_CONSTANTS'=>[
        'KEY_PRACTITIONER_ID' => 'practitioner_id',
        'KEY_FULL_NAME' => 'full_name',
        'KEY_EMAIL' => 'email',
        'KEY_PASSWORD' => 'password',
        'KEY_PHONE' => 'phone',
        'KEY_PROFILE_IMAGE' => 'profile_image',
        'KEY_DEVICE_ID' => 'device_id',
        'KEY_DEVICE_TYPE' => 'device_type',
        'KEY_SOCIAL_ID' => 'social_id',
        'KEY_LOGIN_TYPE' => 'login_type',
        'KEY_STATUS_NOTIFICATION' => 'status_notification',
        'KEY_QUALIFICATION_Id' => 'qualification_id',
        'KEY_PRACTITIONER_CLINICS' => 'practitioner_clinics',
        'KEY_CLINIC' => 'clinic',
        'KEY_DAYS' => 'days',
        'KEY_FROM_TIME' => 'from_time',
        'KEY_TO_TIME' => 'to_time',
        'KEY_PHYSICAL_FEE' => 'physical_fee',
        'KEY_ONLINE_FEE' => 'online_fee',
    ],

];
